# -*- coding: utf-8 -*-
"""testing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ktdT09hWLYrDGXnUo5EcXpqKXP602c2l
"""

import cv2
import time
import threading

class VideoPlayer:
    def __init__(self, source, size=None, flip=False, fps=None, skip_first_frames=0):
        self.__cap = cv2.VideoCapture(source)
        if not self.__cap.isOpened():
            raise RuntimeError(
                f"Cannot open {'camera' if isinstance(source, int) else ''} {source}"
            )
        self.__cap.set(cv2.CAP_PROP_POS_FRAMES, skip_first_frames)
        self.__input_fps = self.__cap.get(cv2.CAP_PROP_FPS)
        if self.__input_fps <= 0:
            self.__input_fps = 30
        self.__output_fps = fps if fps is not None else self.__input_fps
        self.__flip = flip
        self.__size = None
        self.__interpolation = None
        if size is not None:
            self.__size = size
            self.__interpolation = (
                cv2.INTER_AREA
                if size[0] < self.__cap.get(cv2.CAP_PROP_FRAME_WIDTH)
                else cv2.INTER_LINEAR
            )
        _, self.__frame = self.__cap.read()
        self.__lock = threading.Lock()
        self.__thread = None
        self.__stop = False
        self.__cam_counter = 1

    def start(self):
        self.__stop = False
        self.__thread = threading.Thread(target=self.__run, daemon=True)
        self.__thread.start()

    def stop(self):
        self.__stop = True
        if self.__thread is not None:
            self.__thread.join()
        self.__cap.release()

    def __run(self):
        prev_time = 0
        while not self.__stop:
            t1 = time.time()
            ret, frame = self.__cap.read()
            self.__cam_counter += 1
            if not ret:
                break

            if 1 / self.__output_fps <= time.time() - prev_time:
                prev_time = time.time()
                with self.__lock:
                    self.__frame = frame

            t2 = time.time()
            wait_time = 1 / self.__input_fps - (t2 - t1)
            time.sleep(max(0, wait_time))

        self.__frame = None

    def next(self):
        with self.__lock:
            if self.__frame is None:
                return (None, -1)
            frame = self.__frame.copy()
        if self.__size is not None:
            frame = cv2.resize(frame, self.__size, interpolation=self.__interpolation)
        if self.__flip:
            frame = cv2.flip(frame, 1)
        return frame, self.__cam_counter

pip install openvino

import tensorflow as tf
from tensorflow.keras.models import load_model
from imutils import paths

import imageio
import cv2
import os

from IPython import display
import collections
import time
import numpy as np

import multiprocessing
num_cores = multiprocessing.cpu_count()

from openvino.runtime import Core

from keras.models import load_model
from tensorflow.keras.layers import LSTM

class CustomLSTM(LSTM):
    def __init__(self, *args, time_major=False, **kwargs):
        super().__init__(*args, **kwargs)

custom_objects = {"LSTM": CustomLSTM}
decoder = load_model('/content/drive/MyDrive/classifier_lstm_e19.h5',
                     compile=False, custom_objects=custom_objects)

decoder.summary()

IMG_SIZE = (299, 224)
BATCH_SIZE = 30
EPOCHS = 100
MAX_SEQ_LENGTH = 32
NUM_FEATURES = 2048

ie = Core()
model_ir = ie.read_model(model="/content/drive/MyDrive/saved_model.xml")
compiled_model_ir = ie.compile_model(model=model_ir, device_name="CPU")

output_layer_ir = compiled_model_ir.output(0)

try:
    height_en, width_en = list(encoder.inputs[0].shape)[1:3]
except:
    height_en, width_en = list(compiled_model_ir.inputs[0].shape)[1:3]
frames2decode = list(decoder.inputs[0][1].shape)[0]

class_vocab = ['Abuse', 'Arson', 'Assault', 'Burglary', 'Explosion', 'Fighting', 'Normal']

def crop_center_square(frame):
    y, x = frame.shape[0:2]
    min_dim = min(y, x)
    start_x = (x // 2) - (min_dim // 2)
    start_y = (y // 2) - (min_dim // 2)
    return frame[start_y : start_y + min_dim, start_x : start_x + min_dim]

def center_crop(frame: np.ndarray) -> np.ndarray:
    img_h, img_w, _ = frame.shape
    min_dim = min(img_h, img_w)
    start_x = int((img_w - min_dim) / 2.0)
    start_y = int((img_h - min_dim) / 2.0)
    roi = [start_y, (start_y + min_dim), start_x, (start_x + min_dim)]
    return frame[start_y : (start_y + min_dim), start_x : (start_x + min_dim), ...], roi

def rec_frame_display(frame: np.ndarray, roi) -> np.ndarray:
    cv2.line(frame, (roi[2] + 3, roi[0] + 3), (roi[2] + 3, roi[0] + 100), (0, 200, 0), 2)
    cv2.line(frame, (roi[2] + 3, roi[0] + 3), (roi[2] + 100, roi[0] + 3), (0, 200, 0), 2)
    cv2.line(frame, (roi[3] - 3, roi[1] - 3), (roi[3] - 3, roi[1] - 100), (0, 200, 0), 2)
    cv2.line(frame, (roi[3] - 3, roi[1] - 3), (roi[3] - 100, roi[1] - 3), (0, 200, 0), 2)
    cv2.line(frame, (roi[3] - 3, roi[0] + 3), (roi[3] - 3, roi[0] + 100), (0, 200, 0), 2)
    cv2.line(frame, (roi[3] - 3, roi[0] + 3), (roi[3] - 100, roi[0] + 3), (0, 200, 0), 2)
    cv2.line(frame, (roi[2] + 3, roi[1] - 3), (roi[2] + 3, roi[1] - 100), (0, 200, 0), 2)
    cv2.line(frame, (roi[2] + 3, roi[1] - 3), (roi[2] + 100, roi[1] - 3), (0, 200, 0), 2)
    FONT_STYLE = cv2.FONT_HERSHEY_SIMPLEX
    org = (roi[2] + 3, roi[1] - 3)
    org2 = (roi[2] + 2, roi[1] - 2)
    FONT_SIZE = 0.5
    FONT_COLOR = (0, 200, 0)
    FONT_COLOR2 = (0, 0, 0)
    cv2.putText(frame, "ROI", org2, FONT_STYLE, FONT_SIZE, FONT_COLOR2)
    cv2.putText(frame, "ROI", org, FONT_STYLE, FONT_SIZE, FONT_COLOR)
    return frame

def display_text_fnc_modified(frame, display_text, index):
    FONT_COLOR = (255, 255, 255)
    FONT_COLOR2 = (0, 0, 0)
    FONT_STYLE = cv2.FONT_HERSHEY_DUPLEX
    FONT_SIZE = 0.7
    TEXT_VERTICAL_INTERVAL = 25
    TEXT_LEFT_MARGIN = 15

    text_loc = (TEXT_LEFT_MARGIN, TEXT_VERTICAL_INTERVAL * (index + 1))
    text_loc2 = (TEXT_LEFT_MARGIN + 1, TEXT_VERTICAL_INTERVAL * (index + 1) + 1)
    frame2 = frame.copy()
    _ = cv2.putText(frame2, display_text, text_loc, FONT_STYLE, FONT_SIZE, FONT_COLOR)
    return frame2

def display_text_fnc(frame, display_text, index):
    FONT_COLOR = (255, 255, 255)
    FONT_COLOR2 = (0, 0, 0)
    FONT_STYLE = cv2.FONT_HERSHEY_DUPLEX
    FONT_SIZE = 0.5
    TEXT_VERTICAL_INTERVAL = 25
    TEXT_LEFT_MARGIN = 15
    text_loc = (TEXT_LEFT_MARGIN, TEXT_VERTICAL_INTERVAL * (index + 1))
    text_loc2 = (TEXT_LEFT_MARGIN + 1, TEXT_VERTICAL_INTERVAL * (index + 1) + 1)
    frame2 = frame.copy()
    _ = cv2.putText(frame2, display_text, text_loc2, FONT_STYLE, FONT_SIZE, FONT_COLOR2)
    _ = cv2.putText(frame2, display_text, text_loc, FONT_STYLE, FONT_SIZE, FONT_COLOR)
    return frame2

frames_idx = []

def run_action_recognition(
    source: str = '0',
    flip: bool = True,
    skip_first_frames: int = 0
):
    size = height_en
    sample_duration = frames2decode
    fps = 30
    player = None
    final_inf_counter = 0
    final_infer_time = time.time()
    final_infer_duration = 0
    global frames_idx
    frame_counter = None
    try:

        player = VideoPlayer(source, flip=flip, fps=fps, skip_first_frames=skip_first_frames)
        player.start()
        processing_times = collections.deque()
        processing_time = 0
        encoder_output = []
        decoded_labels = [0, 0, 0]
        decoded_top_probs = [0, 0, 0]
        counter = 0
        text_inference_template = "Infer Time:{Time:.1f}ms"
        text_template = "{label},{conf:.2f}%"

        while True:
            counter = counter + 1
            frame, frame_counter = player.next()

            if frame is None:
                print("Source ended")
                break

            preprocessed = cv2.resize(frame, IMG_SIZE)
            preprocessed = preprocessed[:, :, [2, 1, 0]]
            if counter % 2 == 0:
                frames_idx.append((counter, frame_counter, 'Yes'))
                start_time = time.time()
                encoder_output.append(compiled_model_ir([preprocessed[None, ...]])[output_layer_ir][0])

                if len(encoder_output) == sample_duration:
                    frame_mask = np.array([[1]*sample_duration])
                    encoder_output = np.array(encoder_output)[None, ...]
                    probabilities = decoder.predict(encoder_output)[0]
                    for idx, i in enumerate(np.argsort(probabilities)[::-1][:3]):
                        decoded_labels[idx] = class_vocab[i]
                        decoded_top_probs[idx] = probabilities[i]
                    encoder_output = []
                    final_inf_counter += 1
                    final_infer_duration = (time.time() - final_infer_time)
                    final_infer_time = time.time()
                stop_time = time.time()

                processing_times.append(stop_time - start_time)

                if len(processing_times) > 200:
                    processing_times.popleft()

                processing_time = np.mean(processing_times) * 1000
                fps = 1000 / processing_time

            else:
                frames_idx.append((counter, frame_counter, 'No'))
            frame = cv2.resize(frame, (620, 350))
            for i in range(0, 3):
                display_text = text_template.format(
                    label=decoded_labels[i],
                    conf=decoded_top_probs[i] * 100,
                )
                frame = display_text_fnc(frame, display_text, i)

            display_text = text_inference_template.format(Time=processing_time, fps=fps)

            frame = display_text_fnc(frame, display_text, 3)

            frame = display_text_fnc(frame, f"Infer Count: {final_inf_counter}",4)

            _, encoded_img = cv2.imencode(".jpg", frame, params=[cv2.IMWRITE_JPEG_QUALITY, 90])
            i = display.Image(data=encoded_img)
            display.clear_output(wait=True)
            display.display(i)

    except KeyboardInterrupt:
        print("Interrupted")
    except RuntimeError as e:
        print(e)
    finally:
        if player is not None:
            player.stop()

try:
	run_action_recognition(source="/content/drive/MyDrive/DS/testing/Copy of Fighting018_x264.mp4", flip=False, skip_first_frames=34)
except Exception as e:
    print(e)