# -*- coding: utf-8 -*-
"""Training.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1it8Onr_uCusDojMKHJsFI7sakgvSalsK
"""

import os
import glob
import pandas as pd
import numpy as np
from moviepy import editor
from tqdm.notebook import tqdm_notebook

!pip install openvino-dev

def get_time(timestamp, e=0, max_t=None):
    if e>0 and max_t is None:
        print("Please provide max_t")
        return
    if ":" in timestamp:
        minute = int(timestamp.split(":")[0])*60
        second = float(timestamp.split(":")[1])
        t = minute + second
        return max(t+e, 0) if e<0 else min(t+e, max_t)
    else:
        try:
            return max(float(timestamp)+e, 0) if e<0 else min(float(timestamp)+e, max_t)
        except Exception as e:
            print(e)

def get_filename(file, n):
    ext = "."+file.split('.')[-1]
    new_name = file[:-len(ext)] + "_" + str(n) + ext
    return new_name

def extract_clips(data_dir, root="/content/drive/MyDrive/DS", output_root="Processed-Videos", gap=2, skip_classes=[]):
    base_path = os.path.join(root, data_dir)
    if not os.path.exists(base_path):
        print(f"{base_path} does not exists.")
        return
    subdirs = []
    for d in os.listdir(base_path):
        if os.path.isdir(os.path.join(base_path, d)):
            subdirs.append(d)
    for d in subdirs:
        if d in skip_classes:
            continue
        os.mkdir(os.path.join(root, output_root, d))
        file = open(os.path.join(base_path,d, f"{d}_Labels.txt"), mode='r', encoding='utf-8')
        lines = file.readlines()
        print(f"Processing {d} category videos:")
        for line in tqdm_notebook(lines):
            l = line.strip().split()
            vid_name = l[0]
            vid_path = os.path.join(base_path, d, vid_name)
            if os.path.exists(vid_path):
                video = editor.VideoFileClip(vid_path)
                if len(l[1:])%2 != 0:
                    print(f"Timestamps are not in complete pairs. Ignoring last timestamp for video {os.path.join(base_path, d, vid_name)}")
                anomaly_timestamps = []
                # Anamoly part extraction
                n_pairs = len(l[1:])//2
                for n in range(n_pairs):
                    new_vid = f"{os.path.join(root, output_root, d, get_filename(vid_name, n))}"
                    t1, t2 = get_time(l[n*2+1], e=-0.7), get_time(l[n*2+2], e=0.7, max_t=video.duration)
                    if t1 is not None and t2 is not None:
                        clip = video.subclip(t1, t2)
                        clip.write_videofile(new_vid, logger=None)
                        anomaly_timestamps.append((t1, t2))
                    else:
                        print(f"Skipping timestamps pairs {l[n*2+1]} and {l[n*2+2]} for {vid_path}")
                # Normal part extraction
                normal_output_dir = os.path.join(root, output_root, "Normal")
                if not os.path.exists(normal_output_dir):
                    os.mkdir(normal_output_dir)
                normal_timestamps = []
                if len(anomaly_timestamps) > 0:
                    if anomaly_timestamps[0][0]-gap > 0:   # gap b/w normal & anomaly
                        normal_timestamps.append((0, anomaly_timestamps[0][0]-gap))
                    for i in range(len(anomaly_timestamps)-1):
                        start = anomaly_timestamps[i][1]+gap
                        end = anomaly_timestamps[i+1][0]-gap
                        if end-start > 0:
                            normal_timestamps.append((start, end))
                    if anomaly_timestamps[-1][1]+gap < video.duration:
                        normal_timestamps.append((anomaly_timestamps[-1][1]+gap, video.duration))
                for i, t in enumerate(normal_timestamps):
                    if t[1]-t[0]>=1.3:
                        clip = video.subclip(t[0], t[1])
                        new_vid = f"{os.path.join(normal_output_dir, get_filename('Normal_'+vid_name, i))}"
                        clip.write_videofile(new_vid, logger=None)
            else:
                print(f"{vid_path} doesnot exists. Skipping...")

extract_clips("Anomaly-Videos-Part-1")

extract_clips("Anomaly-Videos-Part-2")

def trim_clips(MAX_SEQ_LENGTH=40, output_dir="Trimmed-Videos", input_dir="Processed-Videos", root="/content/drive/MyDrive/DS"):
    import os
    import glob
    from moviepy import editor
    from tqdm.notebook import tqdm as tqdm_notebook
    workspace_output_dir = f"/content/{output_dir}"
    if not os.path.exists(workspace_output_dir):
        os.mkdir(workspace_output_dir)

    for cat in os.listdir(f"{root}/{input_dir}/"):
        cat_output_path = os.path.join(workspace_output_dir, cat)
        os.mkdir(cat_output_path)
        print(f"Processing {cat} category videos:")

        for file in tqdm_notebook(glob.glob(f"{root}/{input_dir}/{cat}/*")):
            video = editor.VideoFileClip(file)
            vid_name = os.path.basename(file).strip()
            fps = video.fps
            interval = (1 / fps) * MAX_SEQ_LENGTH
            t = 0
            counter = 0

            while (video.duration - t) >= interval:
                clip = video.subclip(t, t + interval)
                output_path = os.path.join(cat_output_path, get_filename(vid_name, counter))
                clip.write_videofile(output_path, logger=None)
                counter += 1
                t += interval

            if (video.duration - t) > 1.4:
                clip = video.subclip(video.duration - interval, video.duration)
                output_path = os.path.join(cat_output_path, get_filename(vid_name, counter))
                clip.write_videofile(output_path, logger=None)

            video.close()

trim_clips(MAX_SEQ_LENGTH=64)

import zipfile
import os

zip_path = '/content/drive/MyDrive/Trimmed-Videos.zip'
extract_path = '/content/Trimmed-Videos'

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_path)

import os
import pandas as pd

rooms = []
for item in os.listdir('/content/Trimmed-Videos'):
    files = os.listdir(f'/content/Trimmed-Videos/{item}')
    for file in files:
        rooms.append((item, f'/content/Trimmed-Videos/{item}/{file}'))

df = pd.DataFrame(data=rooms, columns=['label', 'filepath'])
df.head()

df_normal = df[df['label']=='Normal']
df_normal

df_anomaly = df[df['label']!='Normal']
df_anomaly

# Downsampling to balance dataset
import numpy as np
drop_indices = np.random.choice(df_normal.index, 5000, replace=False)
df_normal_subset = df_normal.drop(drop_indices)

df_normal_subset

df_final = pd.concat([df_normal_subset, df_anomaly])
df_final

df_final = df_final.reset_index(drop=True)
df_final

# shuffle the DataFrame rows
df_final = df_final.sample(frac = 1)
df_final

df_final = df_final.reset_index(drop=True)
df_final

test_size = 5000

test_df = df_final.iloc[:5000].reset_index(drop=True)
test_df

train_df = df_final.iloc[5000:].reset_index(drop=True)
train_df

train_df.to_csv("/content/drive/MyDrive/train_df.csv", index=False)

test_df.to_csv("/content/drive/MyDrive/test_df.csv", index=False)

!pip install decord

from decord import VideoReader
from decord import cpu, gpu

import os
import cv2
import pandas as pd
import numpy as np
from tqdm import tqdm
import tensorflow as tf
import matplotlib.pyplot as plt
from tensorflow.keras.layers import Dense, Input, GlobalAveragePooling2D, Flatten
from tensorflow.keras.applications import DenseNet121
from tensorflow.keras.models import Model
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.callbacks import ModelCheckpoint, ReduceLROnPlateau, EarlyStopping
from IPython.display import clear_output
import random

def load_video(path, max_frames=32, resize=(299, 224)):
    vr = VideoReader(path, ctx=cpu(0))
    start = 0
    end = int(max_frames*2)
    if end>len(vr):
      end = len(vr)
    frames_list = list(range(start, end, 2))
    frames_orig = vr.get_batch(frames_list).asnumpy()
    frames = []
    for f in frames_orig:
        frame = cv2.resize(f, resize)
        frames.append(frame)

    if len(frames) < max_frames:
        for i in range(max_frames-len(frames)):
            frames.append(np.zeros((resize[1], resize[0], 3)))
    if len(frames) > max_frames:
        frames = frames[:max_frames]

    return frames

def build_feature_extractor(input_shape=(224, 299, 3)):
    feature_extractor = tf.keras.applications.InceptionV3(
        weights="imagenet",
        include_top=False,
        pooling="avg",
        input_shape=input_shape,
    )
    preprocess_input = tf.keras.applications.inception_v3.preprocess_input

    inputs = tf.keras.Input(input_shape)
    preprocessed = preprocess_input(inputs)

    outputs = feature_extractor(preprocessed)
    return tf.keras.Model(inputs, outputs, name="feature_extractor")

with tf.device('/GPU:0'):
    feature_extractor = build_feature_extractor()
feature_extractor.summary()

def prepare_videos(data_dir="/content/Trimmed-Videos", category=None, output_dir=None, batch_size=32, max_frames=32):
    cat = category
    if not os.path.exists(output_dir):
        os.mkdir(output_dir)

    # Create category folder inside output_dir
    os.makedirs(f"{output_dir}/{cat}", exist_ok=True)

    all_vids = os.listdir(f"{data_dir}/{cat}")
    n_vids = len(all_vids)

    for idx in tqdm(range(n_vids // batch_size)):
        index = idx * batch_size
        batch_vids = all_vids[index:(index + batch_size)]
        encodings = []
        frames = []

        for v in batch_vids:
            frames.extend(load_video(f"{data_dir}/{cat}/{v}", max_frames=max_frames))

        encodings = feature_extractor.predict(np.array(frames), verbose=0).astype(np.float32)

        batch_encodings = []
        for i in range(batch_size):
            start_idx = i * max_frames
            batch_encodings.append(encodings[start_idx:(start_idx + max_frames)])

        batch_encodings = np.array(batch_encodings, dtype=np.float32)
        np.save(f"{output_dir}/{cat}/{cat}_batch_{idx}.npy", batch_encodings)

    del batch_encodings, encodings, frames, all_vids

prepare_videos(data_dir="/content/Trimmed-Videos", category="Abuse", output_dir="/content/Encoded-Videos")

prepare_videos(data_dir="/content/Trimmed-Videos", category="Arson", output_dir="/content/Encoded-Videos")

prepare_videos(data_dir="/content/Trimmed-Videos", category="Assault", output_dir="/content/Encoded-Videos")

prepare_videos(data_dir="/content/Trimmed-Videos", category="Burglary", output_dir="/content/Encoded-Videos")

prepare_videos(data_dir="/content/Trimmed-Videos", category="Explosion", output_dir="/content/Encoded-Videos")

prepare_videos(data_dir="/content/Trimmed-Videos", category="Normal", output_dir="/content/Encoded-Videos")

prepare_videos(data_dir="/content/Trimmed-Videos", category="Fighting", output_dir="/content/Encoded-Videos")

import shutil
from google.colab import drive
shutil.make_archive('/content/Encoded-Videos', 'zip', '/content/Encoded-Videos')

if not os.path.exists("/content/Encoded-Videos-individual"):
    os.mkdir("/content/Encoded-Videos-individual")

for cat in os.listdir("/content/Encoded-Videos"):
    os.mkdir(f"/content/Encoded-Videos-individual/{cat}")
    print(f"Processing {cat} files:")
    for b in tqdm(os.listdir(f"/content/Encoded-Videos/{cat}")):
        batch = np.load(f"/content/Encoded-Videos/{cat}/{b}")
        for i,v in enumerate(batch):
            np.save(f"/content/Encoded-Videos-individual/{cat}/{b.replace('.npy', '')}_{i}.npy", v)
        del batch

import zipfile
import os

zip_path = "/content/drive/MyDrive/Encoded-Videos-individual.zip"

extract_path = "/"

os.makedirs(extract_path, exist_ok=True)
with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_path)

print("✅ Unzipping complete! Files extracted to:", extract_path)

from glob import glob
files = glob("/content/Encoded-Videos-individual/*/*.npy")
len(files)

!zip -r Encoded-Videos-individual.zip /content/Encoded-Videos-individual

rooms = []
for item in os.listdir('/content/Encoded-Videos-individual'):
     files = os.listdir(f'/content/Encoded-Videos-individual/{item}')

     # Add them to the list
     for file in files:
            rooms.append((item, f'/content/Encoded-Videos-individual/{item}/{file}'))

# Build a dataframe
df = pd.DataFrame(data=rooms, columns=['label', 'filepath'])
df_final = df.sample(frac = 1)
df_final = df_final.reset_index(drop=True)

TEST_SIZE = 5000
test_df = df_final.iloc[:TEST_SIZE].reset_index(drop=True)
train_df = df_final.iloc[TEST_SIZE:].reset_index(drop=True)

print(f"Total videos for training: {len(train_df)}")
print(f"Total videos for testing: {len(test_df)}")

train_df.sample(10)

test_df.to_csv("/content/test_df.csv", index=False)
train_df.to_csv("/content/train_df.csv", index=False)

label_processor = tf.keras.layers.StringLookup(num_oov_indices=0, vocabulary=np.unique(train_df["label"]), output_mode='one_hot')
print(label_processor.get_vocabulary())

labels = train_df["label"].values
labels = label_processor(labels[..., None]).numpy()
labels

class DataGenerator(tf.keras.utils.Sequence):
    def __init__(self, df, x_col='filepath', y_col='label', batch_size=32, num_classes=None, shuffle=True):
        self.batch_size = batch_size
        self.df = df
        self.indices = self.df.index.tolist()
        self.num_classes = num_classes
        self.shuffle = shuffle
        self.x_col = x_col
        self.y_col = y_col
        self.on_epoch_end()

    def __len__(self):
        return len(self.indices) // self.batch_size

    def __getitem__(self, index):
        index = self.index[index * self.batch_size:(index + 1) * self.batch_size]
        batch = [self.indices[k] for k in index]

        X, y = self.__get_data(batch)
        return X, y

    def on_epoch_end(self):
        self.index = np.arange(len(self.indices))
        if self.shuffle == True:
            np.random.shuffle(self.index)

    def __get_data(self, batch):

        batch_df = self.df.iloc[batch]
        labels = batch_df[self.y_col].values
        y = label_processor(labels[..., None]).numpy()

        imgs_encodings = []
        for ig in batch_df[self.x_col].values:
            encodings = np.load(ig)
            imgs_encodings.append(encodings)

        X = np.array(imgs_encodings)

        return X, y

IMG_SIZE = (299, 224)
BATCH_SIZE = 32
EPOCHS = 100

MAX_SEQ_LENGTH = 32
NUM_FEATURES = 2048

train_gen = DataGenerator(df=train_df, x_col='filepath', y_col='label', batch_size=BATCH_SIZE)
val_gen = DataGenerator(df=test_df, x_col='filepath', y_col='label', batch_size=BATCH_SIZE)

def get_sequence_model():
    class_vocab = label_processor.get_vocabulary()

    frame_features_input = tf.keras.Input((MAX_SEQ_LENGTH, NUM_FEATURES))
    x = tf.keras.layers.LSTM(256, return_sequences=True)(frame_features_input)
    x = tf.keras.layers.LSTM(128)(x)
    x = tf.keras.layers.Dropout(0.4)(x)
    x = tf.keras.layers.Dense(32, activation="relu")(x)
    output = tf.keras.layers.Dense(len(class_vocab), activation="softmax")(x)

    rnn_model = tf.keras.Model(frame_features_input, output)

    rnn_model.compile(
        loss="categorical_crossentropy", optimizer="adam", metrics=["accuracy"]
    )
    return rnn_model

with tf.device('/GPU:0'):
    seq_model = get_sequence_model()
seq_model.summary()

os.mkdir("Output")

weight_path = "Output2/checkpoint-{epoch:03d}-{val_accuracy:.3f}.weights.h5"

checkpoint = ModelCheckpoint(weight_path, monitor='val_loss', verbose=1,
                             save_best_only=True, mode='min', save_weights_only = True)


early = EarlyStopping(monitor="val_loss",
                      mode="min",
                      patience=8)

CALLBACKS = [checkpoint, early]

history = seq_model.fit(train_gen,
                        validation_data=val_gen,
                        epochs=EPOCHS,
                        callbacks=CALLBACKS)

plt.figure(figsize=(20,6))
for i, met in enumerate(['accuracy', 'loss']):
    plt.subplot(1,2,i+1)
    plt.plot(history.history[met], color="b")
    plt.plot(history.history["val_"+met], color="g")
    plt.title('Model '+met.capitalize())
    plt.xlabel('epochs')
    plt.ylabel(met)
    plt.legend(['train', 'val'])

feature_extractor.save("feature_extractor_inceptionv3.h5")

!mv /content/feature_extractor_inceptionv3.h5 "/content/drive/My Drive/feature_extractor_inceptionv3.h5"

!cp /content/Output2/checkpoint-024-0.921.weights.h5 "/content/drive/My Drive/checkpoint-024-0.921.weights.h5"